* Coordinates
NOTE, unless otherwise specificed, coordinates are in millimeters (mm)

* Coordinate adjustments
In common.py, bottom left board positon when x/y zeroed at home is:
botLeft = (-177.2, -185.3)
Kicad topLeft board corner is at 25.4, 25.4 AND kicad y-direction is flipped from CNC coords.

To get the botLeft board corner at (0, 0) in flatcam, an offset vector of (-25.4, +76.2) is required.


To get the botLeft board corner at (-177.2, -185.3) in flatcam, use the following offset:
*USE FLATCAM OFFSET BELOW*
(-202.6, -109.1)

To check, the bottom left mounting hole should be offset by (+3.175, +3.175) from the botLeft corner, or
(-174.025, -182.125)
I checked and verified this in the flatcam output.

* Exporting drill holes
** 3.175 mm holes 
open base_station.drl in flatcam.
select base_station.drl in flatcam.
*Pick tool with diameter 3.175*

Pick selected tab
scroll down to offset
(offset) vector: (-202.6, -109.1)
click offset

Under create cnc job:
cut z: -2.5
travel z: 40
tool change: leave unchecked
feed rate: 15
spindle speed: 10000
click generate

click project tab
select base_station.drl_cnc
Pick selected tab
click export gcode
In folder fab_outputs.nogit, save as base_station_Carbide3D_101_drill.gcode

click project tab
delete all entries before proceeding to the next step

** 0.7 mm holes 
open base_station.drl in flatcam.
select base_station.drl in flatcam.
*Pick tool with diameter 0.7*

Pick selected tab
scroll down to offset
(offset) vector: (-202.6, -109.1)
click offset

Under create cnc job:
cut z: -2.5
travel z: 40
tool change: leave unchecked
feed rate: 15
spindle speed: 10000
click generate

click project tab
select base_station.drl_cnc
Pick selected tab
click export gcode
In folder fab_outputs.nogit, save as base_station_0p7mm_drill.gcode

click project tab
delete all entries before proceeding to the next step

command line:
sed -i 's/G01 Z-2.5000/G00 Z0.5000\nG01 Z-2.5000/g'  fab_outputs.nogit/base_station_*mm_drill.gcode 
** 0.8 mm holes 
open base_station.drl in flatcam.
select base_station.drl in flatcam.
*Pick tool with diameter 0.8*

Pick selected tab
scroll down to offset
(offset) vector: (-202.6, -109.1)
click offset

Under create cnc job:
cut z: -2.5
travel z: 40
tool change: leave unchecked
feed rate: 15
spindle speed: 10000
click generate

click project tab
select base_station.drl_cnc
Pick selected tab
click export gcode
In folder fab_outputs.nogit, save as base_station_0p8mm_drill.gcode

click project tab
delete all entries before proceeding to the next step

** 0.9 mm holes 
open base_station.drl in flatcam.
select base_station.drl in flatcam.
*Pick tool with diameter 0.9*

Pick selected tab
scroll down to offset
(offset) vector: (-202.6, -109.1)
click offset

Under create cnc job:
cut z: -2.5
travel z: 40
tool change: leave unchecked
feed rate: 15
spindle speed: 10000
click generate

click project tab
select base_station.drl_cnc
Pick selected tab
click export gcode
In folder fab_outputs.nogit, save as base_station_0p9mm_drill.gcode

click project tab
delete all entries before proceeding to the next step

** 1.0 mm holes 
open base_station.drl in flatcam.
select base_station.drl in flatcam.
*Pick tool with diameter 1.0*

Pick selected tab
scroll down to offset
(offset) vector: (-202.6, -109.1)
click offset

Under create cnc job:
cut z: -2.5
travel z: 40
tool change: leave unchecked
feed rate: 15
spindle speed: 10000
click generate

click project tab
select base_station.drl_cnc
Pick selected tab
click export gcode
In folder fab_outputs.nogit, save as base_station_1p0mm_drill.gcode

click project tab
delete all entries before proceeding to the next step

* Exporting isolation routing
** Front isolation routing (this worked)
first went back into kicad, pcbnew:
- changed track/net clearances to 0.51 mm
- changed gnd zone clearance to 0.51 mm
- ran drc, many small problems, big one is pad-to-pad for RN-52
pads were, with 1.5 mm wide with 2 mm spacing
this gives exactly 0.5 mm clearance. 
Changed them to 1.45 mm wide.
- rerouted other nets to have clearance

open base_station-F.Cu.gbr in flatcam.
select base_station-F.Cu.gbr in flatcam.

Pick selected tab
scroll down to offset
(offset) vector: (-202.6, -109.1)
click offset

Under isolation routing:
tool dia: 0.5
Width (# passes): 1
pass overlap: Doesn't matter
combine passes: checked
click generate geometry

click project tab
select base_station-F.Cu.gbr_iso
Pick selected tab
cut z: -0.15
travel z: 1
feed rate: 40
tool dia: 0.5
spindle speed: 10000
multi-depth: leave unchecked
click generate

click project tab
select base_station-F.Cu.gbr_iso_cnc
Pick selected tab
click export gcode
In folder fab_outputs.nogit, save as base_station_isolation_kodiak_0p5_mill_updated3.gcode

Close flatcam

open in bCNC
  ~/ext/bCNC/bCNC ./fab_outputs.nogit/base_station_isolation_kodiak_0p5_mill_updated3.gcode
select editor tab
go to the first block, should be the top right mounting hole circle...
delete everything after M03 S10000 and G4P1 in the block
for steps below, make sure you don't delete the final M5 command if they end up in one of these blocks.
highlight board outline and delete
highlight bottom left mounting hole circles and delete
delete remaining top right mounting hole circle.
Save as: 
base_station_isolation_kodiak_0p5_mill_updated3_mod.gcode
open in emacs,
find and replace 
G01 Z-0.1500
with the following 2 lines
G00 Z0.50000
G01 Z-0.1500

find and replace
G00 Z1.0000
with
G00 Z40.0000

save it.
re open it in bCNC and look it over for any mistakes
Done inspecting?
close bCNC

copy it over
  cp ./fab_outputs.nogit/base_station_isolation_kodiak_0p5_mill_updated3_mod.gcode  ~/ext/gcode
done!
